### ISSUE TITLE
useAlternateColor true breaks everything

### ISSUE THREAD

**Issue by tttptd** [marta-file-manager/marta-issues#508] opened 2019-02-18 03:11 UTC
Setting: behavior > table > useAlternateColor false
Breaks everything in Classic theme (and others). Panels turn to black and it break files list at all.
When switch back to useAlternateColor true - everything works fine.

**Comment by yanex** [comment] 2019-02-22 23:47
Can't reproduce on Marta 0.6.1 (screenshots attached). Could you please attach yours version?

<img width="967" alt="screenshot 2019-02-23 at 02 47 07" src="https://user-images.githubusercontent.com/95996/53277520-587def80-3715-11e9-8e2d-7b2b88859243.png">
<img width="967" alt="screenshot 2019-02-23 at 02 47 13" src="https://user-images.githubusercontent.com/95996/53277522-59af1c80-3715-11e9-9ddb-eea74c0af93d.png">

**Comment by tttptd** [comment] 2019-02-23 02:05
### Classic
<img width="1092" alt="screen shot 2019-02-23 at 08 58 30" src="https://user-images.githubusercontent.com/1280981/53280159-b5939880-3749-11e9-8456-579f31965c7f.png">
<img width="1092" alt="screen shot 2019-02-23 at 09 00 01" src="https://user-images.githubusercontent.com/1280981/53280160-b7f5f280-3749-11e9-81c1-426be6dccc02.png">
<img width="1092" alt="screen shot 2019-02-23 at 09 03 20" src="https://user-images.githubusercontent.com/1280981/53280186-ea9feb00-3749-11e9-8bfc-c5376b0d1ca6.png">

### Kon
<img width="1092" alt="screen shot 2019-02-23 at 09 04 54" src="https://user-images.githubusercontent.com/1280981/53280205-23d85b00-374a-11e9-8aac-3fead8fde22f.png">
<img width="1092" alt="screen shot 2019-02-23 at 09 04 46" src="https://user-images.githubusercontent.com/1280981/53280207-2aff6900-374a-11e9-859a-6897c4da7952.png">

**Comment by tttptd** [comment] 2019-02-23 02:28
MacOS 10.13.6 (17G5019)

**Comment by yanex** [comment] 2019-04-23 10:10
This should be fixed in Marta 0.6.2 released today. Could you please confirm the fix works?

**Closed by yanex** 2019-04-23 10:10 UTC
Labels: bug, major

**Comment by tttptd** [comment] 2019-04-25 02:05
It works, thank you!
