### ISSUE TITLE
Move file copied to clipboard

### ISSUE THREAD

**Issue by brechtm** [marta-file-manager/marta-issues#883] opened 2022-06-10 13:47 UTC
Finder allows moving a file/directory that was copied to the clipboard by means of the Option-Command-V shortcut. It would be great if Martha would also support this. Alternatively, supporting cut (Command-X) in addition to copy (~ Windows) would be good as well.

**Comment by dufferzafar** [comment] 2022-07-18 02:06
Duplicate of #321

**Closed as completed** 2022-07-18 07:40 UTC
