### ISSUE TITLE
._file.ext appears after any action

### ISSUE THREAD

**Issue by promokit** [marta-file-manager/marta-issues#713] opened 2020-12-18 17:51 UTC
I'm not sure is that a bug or a feature. After any action with files in Marta it generates small hidden files with underscore in the beginning. see the screenshot https://take.ms/zcR3e
How to disable those files creation?
P.S. Read whole documentation and Marta's config but not able to find a solution
Marta v.0.8, Big Sur 11.1 (20C69)

**Comment by yanex** [comment] 2020-12-18 17:56
Hello @promokit!
There's no such a feature in Marta, and I'm not aware of such a bug. Can you please leave more information on how to reproduce it? Are you sure this behavior is not caused by some other application or a Marta plugin?

**Comment by promokit** [comment] 2020-12-18 18:02
Seems something wrong in my setup. I just tried to copy files in Finder and get the same issue. Thanks for a quest reply!

**Comment by promokit** [comment] 2020-12-18 18:36
So what I have found out.
Those files are created by apple quarantine feature. Apple stores metadata in resource forks of the files. Some apps don't understand them, so the metadata gets stripped out into "_file.ext" files. Finder app and Commander One are ignoring such kind of files.
This is unique issue I suppose and I have no idea how to reproduce it.

**Comment by yanex** [comment] 2020-12-18 18:52
I suspect it's not about incompatible apps but incompatible file system (that doesn't support resource forks).
Do you edit files on a network storage or inside a non-native file system?

**Comment by promokit** [comment] 2020-12-18 18:56
That's it! It happens only with files on a network storage

**Comment by yanex** [comment] 2020-12-18 18:57
I'll try to reproduce the issue and look why the files are not hidden as they should.
(Btw they can be shown just because you enabled the "Show hidden files" option. Isn't it the case?)

**Comment by promokit** [comment] 2020-12-18 19:02
Yes, of course I have enabled "Show hidden files" option. 
I don't force you to search a solution, it seems not your problem.

**Comment by yanex** [comment] 2021-04-22 19:34
Thanks for the investigation again!
As the behavior is not related to Marta, I'll close the issue.

**Closed by yanex** 2021-04-22 19:34 UTC
