### ISSUE TITLE
File list does not update when there's a new file

### ISSUE THREAD

**Issue by user3587412** [marta-file-manager/marta-issues#372] opened 2018-06-28 15:17 UTC
Marta does not detect and refresh the file list when there is a new file added to the directory. 

Marta version: 0.5.2, although I think I saw the same issue since 0.5.1

**Comment by krupenja** [comment] 2018-06-29 09:09
Confirm that I also have this with Marta 0.5.2.

**Comment by yanex** [comment] 2018-07-06 23:13
Duplicate of https://github.com/marta-file-manager/marta-issues/issues/380, will be fixed in 0.5.3.

**Closed** 2018-07-06 23:14 UTC
Labels: bug, critical, duplicate/invalid
