### ISSUE TITLE
"=" is not opening Operation queue

### ISSUE THREAD

**Issue by sceptiq** [marta-file-manager/marta-issues#356] opened 2018-06-06 13:44 UTC
Hey, 

Im running ```Version 0.5 (0.5)``` starting a file copy and pressing ```=``` does not open the operation queue.

cheers

**Comment by yanex** [comment] 2018-06-17 20:40
Can't reproduce :(
A queue window is only shown when there is an in-progress async operation. Do you have one?

**Comment by sceptiq** [comment] 2018-06-18 09:58
i do:

(https://www.dropbox.com/s/8x0jm5025gfl4ux/martasQueue.mov?dl=0)

how can i help debugging? what informations may help?

**Comment by yanex** [comment] 2018-06-19 00:00
Did you set a custom hotkey for the `core.show.operation.queue` action?

**Comment by yanex** [comment] 2018-06-19 00:02
Are you about the `|` symbol?
There's a `\` key on my keyboard, and I just press it with `Shift`.
What keyboard layout do you have?

**Comment by sceptiq** [comment] 2018-06-19 08:38
nope.

this is my config:

```json
// This is the user configuration. It is empty by default.

// All possible keys are described in the default configuration file.
// To open it, run the "Open default configuration" action.

{
  "behavior": {
        // Active theme
        "theme": "Snazzy"
      },
  "gadgets": [
    {
        "id": "gadget.sublime", // an action identifier
        "name": "Open in Sublime Text Editor",
        "type": "application",
        "application": "Sublime Text",
        "files": [ "${active.selection.paths}" ]
    }
  ],
  "etty": {
    "theme": "Snazzy",
    "useMainThemeColors": false,
    "fonts": {
       "normal": ["AnonymicePowerline", 11],
       "bold": ["AnonymicePowerline", 11]
    },
  }
}
```

**Comment by krupenja** [comment] 2018-07-22 22:20
Could this be related to #398? If the title bar is not shown (as in that issue), pressing "=" does nothing for me.

**Comment by yanex** [comment] 2019-01-06 16:46
@sceptiq Can you please check if your bug is a duplicate of #398?

**Comment by sceptiq** [comment] 2019-01-17 14:13
not sure if i understand how these two things correlate but...:

i never used marta in fullscreen if that helps :)

**Comment by yanex** [comment] 2019-01-17 14:22
Does the bug reproduce in Marta 0.6?

**Comment by sceptiq** [comment] 2019-01-17 14:49
pressing f5 for copy job ... upper right corner shows a progressbar.

- left-click on the bar shows the pop up / queue. 
- pressing "=" (shift+0 => german layout) nothing happens. 

(Version 0.6 (0.6))

**Closed** 2019-01-17 17:39 UTC
Labels: bug, critical, fixed
