### ISSUE TITLE
colorHighlighting: newly created folder does not have proper highlighting

### ISSUE THREAD

**Issue by krupenja** [marta-file-manager/marta-issues#496] opened 2019-02-09 18:56 UTC
1. Make sure that `colorHighlighting` is enabled.
2. Create a folder in Marta.

The folder is created but is highlighted white (like a file) and not blue (like a folder). If you navigate away from the folder and then navigate back, it is highlighted properly. Reproducible at least with Kon and Dark themes.

**Comment by yanex** [comment] 2019-03-03 04:21
Duplicate of #497.

**Closed by yanex** 2019-03-03 04:21 UTC
Labels: bug, major
