### ISSUE TITLE
Please add support for browsing tarballs

### ISSUE THREAD

**Issue by rbZend** [marta-file-manager/marta-issues#238] opened 2018-02-05 11:12 UTC
Browsing tarballs is the only critically missing functionality for me. Of course, I mean primarily TAR.GZ.

**Comment by monouser7dig** [comment] 2018-02-05 11:20
duplicate of #237 ?

**Comment by rbZend** [comment] 2018-02-05 11:33
Just TAR and TAR.BZ would be nice, too. But you're right, seems to be a duplicate.

**Comment by yanex** [comment] 2018-02-06 01:42
Closed as duplicate.

**Closed by yanex** 2018-02-06 01:42 UTC
Labels: duplicate/invalid
