### ISSUE TITLE
Please allow completely disabling the 2nd pane

### ISSUE THREAD

**Issue by eugenesvk** [marta-file-manager/marta-issues#925] opened 2022-10-30 16:42 UTC
First of all, thanks a bunch for creating this File Manager, it has some rather good fundamentals (keyboard-focus with breadth of shortcuts customization, sublime-like command palette, plugins in a sane language, etc.), so it has the potential to finally become the sorely missed __great file manager__ on a __Mac__ and succeed where FMan stopped!

However, the __dual-pane__ is not great as the permanent default — multiple tabs cover most of its uses and don't waste so much screen real estate (though it has its temporary uses as well when you need to have immediate visibility between the source and the target folders)!
Would you please add an option to __completely disable__ the __second pane__ so that, e.g.
  - <key>Tab</key> would switch between files (including being limited to only those matching the typed text just like ↑↓ arrow keys do) instead of switching between panes as it's currently is even when the second pane is resized to be made invisible
  - copy/... commands would copy "to buffer" and require a paste counterpart command to actually insert files at the new tab (just like in Finder). Other commands that don't make sense with a single pane should just be disabled instead of operating on the hidden 2nd pane
  - the toolbar with command cheatsheet at the bottom should close when the 2nd pane is closed
  - the column layout should be mode-specific (I would have more columns in a single pane than in two panes)
  - etc.
Thanks!

P.S.
By the way, if you need any additional inspiration :), you might want to check out the best Windows file manager — [Directory Opus](https://www.gpsoft.com.au/index.html)

**Comment by page-down** [comment] 2022-10-31 12:14
duplicate of https://github.com/marta-file-manager/marta-issues/issues/611

Replying to the existing issue helps to gather suggestions and ideas for the same subject, instead of being scattered across multiple duplicate GitHub issues.

**Comment by eugenesvk** [comment] 2022-10-31 14:39
Thanks, I did search to via `disable second pane`, but didn't find anything since it was worded differently

Also, the 0% zooming suggestion there is not what I'm looking for, that's how I'm testing Marta with, I  know it from some other dual pane managers, but it's a poor substitute

**Closed as completed** 2022-10-31 14:43 UTC
