### ISSUE TITLE
Remember terminal height

### ISSUE THREAD

**Issue by vedmant** [marta-file-manager/marta-issues#1031] opened 2024-02-15 04:51 UTC
Probably related to https://github.com/marta-file-manager/marta-issues/issues/1017

When I open terminal it always takes most of the window height and doesn't remember when I adjust the height.

https://github.com/marta-file-manager/marta-issues/assets/5052406/95350ff9-360a-46cf-b0e5-b15383fe4044

Sonoma 14.2.1 (23C71)
Marta 0.8.1

**Comment by yanex** [comment] 2024-04-13 16:06
Seems like duplicate of #1017.

**Closed as completed by yanex** 2024-04-13 16:06 UTC
Labels: bug, duplicate, major
