### ISSUE TITLE
Minimized app window does not appear when switching apps

### ISSUE THREAD

**Issue by bjorsen** [marta-file-manager/marta-issues#420] opened 2018-08-27 12:24 UTC
When Marta's main window has been minimized and you're working in another app, you cannot easily return to Marta by command tabbing to it. When you select Marta this way, the app becomes active but the window remains minimized so no actions can be taken.

Ideally when the app becomes active again, the window would be restored.

**Comment by Dvornik** [comment] 2018-09-29 20:53
Confirmed. I hope this will be fixed, this is the only thing that breaks the workflow. Thank you for this great product!

**Comment by yanex** [comment] 2018-10-15 18:00
@bjorsen @Dvornik Looks like other applications behave the same. I've tried Mail.app and iTerm, and none of them automatically show the minimized window.
Can you please provide an example of application that normalizes its window on switching?

**Comment by bjorsen** [comment] 2018-10-15 19:07
Hi,

You are right. Apparently this is (now?) default MacOS behaviour. I am
encountering it with all other applications too. Still feels unintuitive to
switch to an app by keyboard shortcut and not being able to do anything
(until you pick up the mouse though).

**Comment by dguendisch** [comment] 2018-10-15 19:48
While I personally don't like this behaviour of minimized apps, I don't recall that it ever was different.
It was an issue at least 2010: https://www.macworld.com/article/1152366/os-x/commandtabminimizedwindows.html
:)

**Comment by Dvornik** [comment] 2018-10-16 14:30
Wow! OK :) 

> Can you please provide an example of application

I tested it on telegram ([native Mac client](https://macos.telegram.org)). But it seems this is an exception.

**Closed as completed** 2018-10-21 03:21 UTC
Labels: bug, as designed, major
