### ISSUE TITLE
Dynamic Light/Dark Mode of classic.theme 

### ISSUE THREAD

**Issue by lytoooo0** [marta-file-manager/marta-issues#708] opened 2020-12-08 16:13 UTC
Is it possible to detect system appearance in xxx.theme file, so that we can set two appearance (light mode & dark mode) of one theme, and can switch automaticity as system change the appearance.

**Comment by igor-krupenja** [comment] 2020-12-09 11:50
This is planned for 0.8.1, see https://github.com/marta-file-manager/marta-issues/issues/626

**Comment by notDavid** [comment] 2022-07-10 08:14
@lytoooo0 Please close this issue, as this is a duplicate of 626...

**Closed** 2022-07-10 08:18 UTC
