### ISSUE TITLE
Error when moving in Trash (deleting) on FUSE mount and network shares

### ISSUE THREAD

**Issue by ww7** [marta-file-manager/marta-issues#472] opened 2019-01-19 21:33 UTC
I use sshfs/ftp local mounts (FUSE mount) of remote servers and browse with Marta.
Found error (not able to delete) when moving in Trash on mounted remote's.
Finder do it.

**Comment by ww7** [comment] 2019-01-21 14:46
Also not able to delete in network shares (mounted smb)

**Comment by krupenja** [comment] 2019-02-02 23:34
This is probably the same as #147

**Comment by ww7** [comment] 2019-02-02 23:39
> This is probably the same as #147

Yes. My inattention. Maybe just one button (Cancel or Abort) will be more clear

**Comment by yanex** [comment] 2019-04-28 21:56
Closing as duplicate of #147.

**Closed by yanex** 2019-04-28 21:56 UTC
