### ISSUE TITLE
CoreUI: RunTimeThemeRefForBundleIdentifierAndName() couldn't find Assets.car fault

### ISSUE THREAD

**Issue by VKondakoff** [marta-file-manager/marta-issues#600] opened 2019-10-14 10:50 UTC
I'm seeing 'CoreUI: RunTimeThemeRefForBundleIdentifierAndName() couldn't find Assets.car' errors and faults in Console when trying to open Marta preferences for the first time after Marta launch:

<img width="998" alt="image" src="https://user-images.githubusercontent.com/230824/66746071-81f8b080-ee89-11e9-8538-585c81c6579e.png">

Marta 0.7, Catalina

**Comment by yanex** [comment] 2019-11-19 18:32
Hm... Could you please try Marta 0.7.1? Is the error still shown in the new version?

**Comment by yanex** [comment] 2020-07-05 16:58
Unfortunately, I couldn't reproduce the bug, so I will close it as "Can't reproduce".
Please add a comment (or file a new bug) if you still experience it.

**Closed by yanex** 2020-07-05 16:58 UTC
Labels: bug, major
