### ISSUE TITLE
Add option to put the preview in the inactive pane

### ISSUE THREAD

**Issue by yusernamelol** [marta-file-manager/marta-issues#519] opened 2019-03-03 11:54 UTC
If you preview images that are larger than icons, the Quicklook modal obstructs the file list. You either navigate blindly, or toggle the preview on and off, both rather unpleasant, especially if the images vary in size. Enclosing the preview in the inactive pane would solve both problems. Total Commander has this option, and on the Mac, Nimble Commander does it.

**Comment by ad-si** [comment] 2019-03-06 14:12
Just came to the issue tracker to open this issue. I'm glad somebody else did it already 😛.

**Comment by yanex** [comment] 2019-04-28 22:15
Will close as a duplicate of #292.

**Closed** 2019-04-28 22:15 UTC
Labels: duplicate/invalid
