### ISSUE TITLE
Fix delay between consequent "Toggle hidden files" executions

### ISSUE THREAD

**Issue by ghost** [marta-file-manager/marta-issues#306] opened 2018-03-30 22:16 UTC
ctrl+h reveals/ shows hidden files immediately but the help text at the bottom has a _very_ noticeable delay 

this is minor and picky but maybe easy to fix

**Comment by yanex** [comment] 2018-03-30 22:20
@monouser7dig Hm, I can't reproduce this.
The text you see ("Hidden files are not shown anymore") is just a notification message. Notifications are shown in a queue, so in case if you already have some notification shown, the next one will be shown with a delay.

**Comment by monouser7dig** [comment] 2018-03-30 22:25
[show.mov.zip](https://github.com/marta-file-manager/marta-issues/files/1864905/show.mov.zip)

this is realtime video, no background tasks

**Comment by monouser7dig** [comment] 2018-03-30 22:27
I think I see your point though, the "hidden files are now shown" takes some time and thus the "hidden files are not shown anymore" can't be shown directly.

Okay.

**Comment by yanex** [comment] 2018-03-30 22:27
@monouser7dig Well, a notification message **is** a task. So when you press Cmd+H a number of times, Marta submits an equal number of "notification tasks" to the queue.
The problem is that notifications will the same type should probably override ones that was submitted earlier. I will think about this, thanks!

**Comment by monouser7dig** [comment] 2018-03-30 22:31
Yes ok it's not as easy as I first thought. Just read your [blog post](https://marta.yanex.org/marta-goes-beta) and ` I’m the most active user of Marta, and, to be honest, I’m very picky.` motivated me to write this down.

But `Don’t hesitate to thank software developers for their products. It’s really heartwarming!` Marta is still feeling great 👍 
(and 0.5 already is in [homebrew](https://github.com/defaltus/homebrew-cask/blob/ad52e0329ec7859783be98e7cddc501eb358c61b/Casks/marta.rb), even with correct deletion instructions)

**Comment by yanex** [comment] 2018-03-30 22:36
@monouser7dig I agree this behavior is straight-forward in theory, but in practice it turns out to be misleading. Will be fixed for sure.
Thanks for adding to cask! Actually, the update url have changed, it's `https://updates.marta.yanex.org/release/` since 0.5. I can update it later, just caught a cold and need some sleep now 😃 .

**Closed** 2019-01-17 17:13 UTC
Labels: feature, fixed
