### ISSUE TITLE
Marta does not seem to preserve modified time on network shares

### ISSUE THREAD

**Issue by user3587412** [marta-file-manager/marta-issues#622] opened 2019-12-28 13:32 UTC
If you move an item to an smb share, the modified time will not be preserved.

**Comment by yanex** [comment] 2020-07-05 18:04
Unfortunately, I can't reproduce the bug :( In my case, both created and modified times are copied properly.
Can you please add a video and/or add any additional information that may be unique to your use-case?

**Comment by user3587412** [comment] 2020-07-15 01:28
Sorry for the late reply. Here's a gif. The only particular thing that I can think of is that the smb share is mounted via Finder and authenticated.

![Kapture 2020-07-14 at 20 26 22](https://user-images.githubusercontent.com/8388844/87492586-7bfa5080-c610-11ea-8a93-39b45b202760.gif)

**Comment by user3587412** [comment] 2020-11-13 18:42
Issue with copying files and preserving the modified time has been fixed with #688, but I'm getting this error when attempting to move the file to an smb share now.

<img width="420" alt="Screen Shot 2020-11-13 at 12 40 25 PM" src="https://user-images.githubusercontent.com/8388844/99108828-84a66780-25ad-11eb-9c7a-881f0b2037fa.png">

**Comment by yanex** [comment] 2020-11-25 18:01
@user3587412 Thanks for the report! Will be fixed in 0.8 release.

**Closed by yanex** 2020-11-25 18:01 UTC
Labels: bug, fixed

**Comment by user3587412** [comment] 2020-11-28 12:23
0.8 RC1 is working perfectly. Thank you! It is so very nice to be back to Marta. Using Forklift this past year was miserable.
