### ISSUE TITLE
New goto should support other volumes as well

### ISSUE THREAD

**Issue by warpkanal** [marta-file-manager/marta-issues#211] opened 2017-12-17 20:41 UTC
Looks like goto doesn't find and doesn't complete on folders located on other volumes.
Would be great if it would :)
Second: what do you think about Goto ordering entries in a kind of last-used fashion? So that if I enter some folders regularly they are kind of "boosted" and located on the top of the list?

**Comment by yanex** [comment] 2017-12-17 20:55
Do you mean it does not work for absolute paths (paths starting with `/` or `~`), or for relative paths?

As about ordering, it's a nice feature though it requires some time to implement it carefully. So I afraid it won't be done in the nearest feature. But anyway, it would be very nice if you create an issue for that.

**Comment by warpkanal** [comment] 2017-12-17 21:01
Both styles (absolute and relative) do not show folders from my other volumes.
I'll add a feature request for ordering.

**Comment by warpkanal** [comment] 2017-12-18 06:44
Hmm, maybe it was my misunderstanding, guess the new Goto is as well based on spotlight?
I've intentionally disabled spotlight on that other volumes :)

**Comment by yanex** [comment] 2017-12-18 08:16
Did you mean the "Look up" action? There's also "Go to path" available.

*Look up* for absolute paths is not based on Spotlight. And it works for me (screenshot attached).
<img width="847" alt="screen shot 2017-12-18 at 17 14 00" src="https://user-images.githubusercontent.com/95996/34096024-20af4f24-e417-11e7-8825-fad7cdf421c1.png">

**Comment by yanex** [comment] 2017-12-18 08:21
I've also created this issue: https://github.com/marta-file-manager/marta-issues/issues/213, please check if it sounds like yours.

**Comment by warpkanal** [comment] 2017-12-18 09:15
I mean the "Look up" action. First of all, sorry, you are right, absolute paths do work, I "used" it wrong :)
Second, it's only the relative ones that don't work on other volumes, see screenshot.
![monosnap 2017-12-18 10-13-23](https://user-images.githubusercontent.com/3669157/34098370-5a442a9c-e3dc-11e7-80cc-2b39bd006361.png)

**Comment by yanex** [comment] 2018-01-01 15:44
So now it looks like this is a duplicate of #213.
I will close this issue if you don't mind (and if I don't overlook something).

**Closed** 2018-01-05 15:36 UTC
Labels: bug
